# In class practice with Pandas & Scipy Libraries

Import the libraries

In [1]:
import os
import re
import pandas as pd
from scipy import stats

hello world

## Working with pandas

How to importa a tab-delimited text data file. The file is in the same directory at the jupyter notebook.

In [2]:
data=pd.read_csv('hist_taxa_treat2.txt', sep='\t', index_col=False, low_memory=False)

How to use pandas to assign data from the dataset to a variable.

In [6]:
lacto=data.loc[(data['Species']=='Lactobacillus')]
x=lacto['Abundance']
print('lactos')
print(x)

lactos
0     0.063575
1     0.030630
2     0.026108
3     0.058233
4     0.092633
        ...
84    0.003580
85    0.016010
86    0.044609
87    0.007296
88    0.003000
Name: Abundance, Length: 89, dtype: float64

In [7]:
para=data.loc[(data['Species']=='Parabacteroides')]
#print(para)
y=para['Abundance']
print('paras')
print(y)

paras
89     0.005896
90     0.001962
91     0.002219
92     0.003267
93     0.002320
         ...
173    0.003376
174    0.002668
175    0.012194
176    0.020810
177    0.006534
Name: Abundance, Length: 89, dtype: float64

## Working with Scipy statistic methods

In [8]:
tt_out=stats.ttest_ind(x,y)
print(tt_out)

Ttest_indResult(statistic=7.288016524628964, pvalue=1.0200357215755368e-11)

## Exercises

PRINT HEAD AND TAIL OF data

Assign 3 variables to 3 different values in column 'Species'

Use the describe function

Print the sums, var, and std for data

Make a new dataframe that only includes SampleID and Species.
Make a second dataframe that only includes only Abundance.
Make a third dataframe that merges the other two.

In [9]:
data.head()

  SampleID Treatment  Treatment_no  Time        Species  Abundance   Count
0    CC01A   Control           1.0   0.0  Lactobacillus   0.063575  1430.0
1    CC01B   Control           1.0   1.0  Lactobacillus   0.030630   379.0
2    CC01C   Control           1.0   2.0  Lactobacillus   0.026108   386.0
3    CC01D   Control           1.0   3.0  Lactobacillus   0.058233  1193.0
4    CC02A   Control           1.0   0.0  Lactobacillus   0.092633  2455.0

In [10]:
data

,SampleID,Treatment,Treatment_no,Time,Species,Abundance,Count
0,CC01A,Control,1.0,0.0,Lactobacillus,0.063575,1430.0
1,CC01B,Control,1.0,1.0,Lactobacillus,0.030630,379.0
2,CC01C,Control,1.0,2.0,Lactobacillus,0.026108,386.0
3,CC01D,Control,1.0,3.0,Lactobacillus,0.058233,1193.0
4,CC02A,Control,1.0,0.0,Lactobacillus,0.092633,2455.0
...,...,...,...,...,...,...,...
1330,CC23C,Treatment,NaN,NaN,Desulfovibrionaceae,0.000000,NaN
1331,CC23D,Treatment,NaN,NaN,Desulfovibrionaceae,0.000000,NaN
1332,CC24A,Treatment,NaN,NaN,Desulfovibrionaceae,0.000203,NaN
1333,CC24B,Treatment,NaN,NaN,Desulfovibrionaceae,0.000063,NaN
1334,CC24D,Treatment,NaN,NaN,Desulfovibrionaceae,0.000000,NaN

## You can use the directory function to see all the pandas methods

In [11]:
#dir(data)

In [20]:
#How to see the names of all the columns
data.columns  #All the titles for the columns

Index(['SampleID', 'Treatment', 'Treatment_no', 'Time', 'Species', 'Abundance',
       'Count'],
      dtype='object')

In [21]:
#Using a for loop to print all the names
for i in data.columns: print (i)

SampleID
Treatment
Treatment_no
Time
Species
Abundance
Count

In [22]:
#Retrieve data of all the columns
data["Count"]

0       1430.0
1        379.0
2        386.0
3       1193.0
4       2455.0
         ...
1330       NaN
1331       NaN
1332       NaN
1333       NaN
1334       NaN
Name: Count, Length: 1335, dtype: float64

In [23]:
#An example of calculating a stat
data["Count"].sum()

233173.0

## Use pandas in a function

Write a function called calc_stats that:
(1) Takes 2 string arguments, a filename of tab-delimited database and the name of a 
    column in the data.
(2) And it returns a list of the following: the sum, median, mean, standard deviation,
    minimum value, and maximum value.

In [1]:
def calc_stats():
    return

In [53]:
out=calc_stats("hist_taxa_treat2.txt", "Count")
print(out)
#Should print [233173.0, 28.0, 218.32677902621722, 448.92572275301353, 0.0, 4317.0]

[233173.0, 28.0, 218.32677902621722, 448.92572275301353, 0.0, 4317.0]

In [54]:
out2=calc_stats("hist_taxa_treat2.txt", "Abundance")
print(out2)
#Should print [14.939201413, 0.001127497, 0.011190413043445693, 0.024424991167155383, 0.0, 0.206321962]

[14.939201413, 0.001127497, 0.011190413043445693, 0.024424991167155383, 0.0, 0.206321962]